### PR TITLE
Allow null value matching in JSON schema where string is expected but not required

### PR DESCRIPTION
**Pull request by Chen2x**
Addressing some of the feedback received during Connect for allowing null responses when a string may be the expected response. This was done by added null to the list of acceptable response types in the json schema.

### CODE REVIEW

**Comment by yash-puligundla** [comment]
@Chen2x Looks good! I have a few minor suggestions that I'd like to share. Although these suggestions may not be directly related to this ticket, it would be beneficial to include them here so that we don't overlook them.

-  v1.2.0/drs_bundle.json
    - since `contents` array is required, add "minItems":1 to `contents` property (that way we make sure contents array is not required and is not empty)
    - since `access_methods` is optional for bundles, remove "minItems":1
- v1.2.0/drs_object.json
    - add `access_methods` to required list
- Make the same changes to v1.3.0 schemas. Also, consider adding drs_bundle.json in v1.3.0 as well, so we don't lose track of the changes we are making as a part of this PR.   

Let me know if you have any questions.

**Comment by Chen2x** [comment]
Since v1.3.0 doesnt use bundles shouldnt we leave that schema out of v1.3.0 to avoid confusion?

**Comment by yash-puligundla** [comment]
> Since v1.3.0 doesnt use bundles shouldnt we leave that schema out of v1.3.0 to avoid confusion?

Hi @Chen2x. I was under the same impression, but, looks like bundles is not deprecated as per [v1.3.0 documentation](https://ga4gh.github.io/data-repository-service-schemas/preview/release/drs-1.3.0/docs/#tag/Objects/operation/GetObject) and [openapi schema](https://github.com/ga4gh/data-repository-service-schemas/blob/master/openapi/components/schemas/DrsObject.yaml)

**Comment by Chen2x** [comment]
@yash-puligundla I have added the bundles schema to v1.3.0

**Review by yash-puligundla — APPROVED** [review]
@Chen2x Everything looks great!

**Pull request merged**
