### PR TITLE
Use ga4gh-testbed-lib to generate report object

### PR DESCRIPTION
**Pull request by yash-puligundla**

### CODE REVIEW

**Comment by emre-f** [comment]
@yash-puligundla Is this PR about running the unit tests?

1. Can I confirm the functionality of this PR by running the unit tests with different kinds of `auth` as described in the `README.md`?
2. I assume the conflicting files are because of the future PRs since they were rebased? I will just choose the files in the `develop` to resolve the conflicts in this case.

**Comment by yash-puligundla** [comment]
> @yash-puligundla Is this PR about running the unit tests?
> 
> 1. Can I confirm the functionality of this PR by running the unit tests with different kinds of `auth` as described in the `README.md`?

Hi @emre-f, you can confirm the functionality by spinning the good_mock_server for each of the auth_types (none, basic, bearer, passport) and running the report on the good_mock_server. The expected behavior is that all the tests pass. 

> 2. I assume the conflicting files are because of the future PRs since they were rebased? I will just choose the files in the `develop` to resolve the conflicts in this case.

I have resolved the conflicts by choosing the files from the current branch (yp_use_testbed_lib) as these are the latest changes

Once, this PR is approved and merged, I will rebase the other branches to the new develop

**Comment by emre-f** [comment]
Hello @yash-puligundla, when I run the `report_runner.py` I get an error on lines 42, 43, 44. Variables called `TESTBED_NAME`, `TESTBED_VERSION` and `TESTBED_DESCRIPTION` are used, but they are not defined. Am I doing something wrong?

**Comment by yash-puligundla** [comment]
@emre-f I have added instructions to create and set up virtual env. Please let me know if you find anything else. Thanks!

**Review by emre-f — APPROVED** [review]
All the unit tests work as intended.

**Pull request merged**
