### PR TITLE
Provide an option to serve output report as HTML

### PR DESCRIPTION
**Pull request by yash-puligundla**
- added a light weight flask app + html + css for rendering the output report as html webpage
- To run the compliance suite and serve the output as HTML, use the following command
`python compliance_suite/report_runner.py --server_base_url "http://localhost:8085/ga4gh/drs/v1" --platform_name "ga4gh starter kit drs" --platform_description "GA4GH reference implementation of DRS specification" --auth_type "none" --drs_version "1.2.0"`

Let me know if you have any questions

### CODE REVIEW

**Comment by yash-puligundla** [comment]
@alextsaihi Is the good_mock_server running at port 8085?

**Comment by alextsaihi** [comment]
Oh right, I forgot that I had the mock server shut down since I rebooted my computer 😅
The output json report is good, 
Although I'm not seeing the HTML being rendered onto http://127.0.0.1:8085/ or http://localhost:8085/

**Comment by yash-puligundla** [comment]
@alextsaihi Please refer to the README doc for the port where the HTML is available

**Comment by alextsaihi** [comment]
Oh ok sorry now I feel dumb.

Using --serve and --serve_port flags didn't raise any issues and webpage looks good to me 😁 I think it could be merged!

**Review by alextsaihi — APPROVED** [review]
it works

**Pull request merged**
