### PR TITLE
Add tests and cases

### PR DESCRIPTION
**Pull request by yash-puligundla**
- some test cases for service-info and drs object info endpoints
 - json report generation in the schema defined by [ga4gh-testbed-lib](https://github.com/ga4gh/ga4gh-testbed-lib/tree/main/schema)
 - some interactions for service-info and drs object info endpoints that provides the details of the http request and expected response
 - report_runner.py will run all the tests and cases and create the final json report output

### CODE REVIEW

**Comment by yash-puligundla** [comment]
@emre-f I have added README.md which has the instructions on how to run the report. The report output will be available in the "output/report*json" file. Let me know if you have any questions.

**Comment by emre-f** [comment]
I also want to note that currently it doesn't work unless DRS is running on port 5000. I see that the port is hard coded in `drs_object.json` and `service_info.json`. I think we should make that a modifiable variable, because by default DRS runs on 4500. Also different people could be running DRS from different ports.

**Comment by yash-puligundla** [comment]
@emre-f Did you pull the latest changes?

**Comment by emre-f** [comment]
@yash-puligundla I pulled the changes now. The different ports work, so you can disregard that part. But the first comment about changing how we path is constructed stands. The `report_runner.py` **only** works if my current directory is the `drs-compliance-suite`, if I cd into `/compliance_suite/` and run it it doesn't work because paths inside it are hard-coded.

**Comment by yash-puligundla** [comment]
> @yash-puligundla I pulled the changes now. The different ports work, so you can disregard that part. But the first comment about changing how we path is constructed stands. The `report_runner.py` **only** works if my current directory is the `drs-compliance-suite`, if I cd into `/compliance_suite/` and run it it doesn't work because paths inside it are hard-coded.

Hi @emre-f, This is the expected behavior as per the design

**Review by emre-f — APPROVED** [review]
test results are correctly created, good to be committed

**Pull request merged**
